server.port=8082
spring.application.name=payment-service

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*


#========================
# POSTGRESQL CONFIG
# ========================

spring.datasource.url=jdbc:postgresql://localhost:5432/orderkafkadb
spring.datasource.username=postgres
spring.datasource.password=1

spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA
# ========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

